before_commands:
    - "composer install --prefer-source"

tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["bin", "spec", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["bin", "spec", "vendor"]