language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer update --prefer-source; composer install --dev --prefer-source;

script:
  - phpunit
  - php bin/coverage-checker.php clover.xml 95